"""empty message

Revision ID: ef349481a01d
Revises: 52973f091505
Create Date: 2022-09-09 12:33:34.455297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef349481a01d'
down_revision = '52973f091505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'views')
    # ### end Alembic commands ###
